### ISSUE TITLE
log when an l1 > l2 deposit tx is sent

### ISSUE THREAD

**Issue by jakim929** [ethereum-optimism/supersim#150]
can be confusing if nothing is logged since it's one of the first steps in the Getting started guide

**Comment by Ethanol48** [comment]
Can I work on it??

**Comment by jakim929** [comment]
@Ethanol48 assigned! let me know if u run into anything

**Comment by Ethanol48** [comment]
Just small question for a little guidance, the log should be in the part of execution in Go and not in Solidity rigth?

I've been exploring the repo and found this folder called [bindings](https://github.com/ethereum-optimism/supersim/blob/main/bindings) am I in the good direction or not?

**Comment by Ethanol48** [comment]
Could 

> @Ethanol48 assigned! let me know if u run into anything

Just small question for a little guidance, the log should be in the part of execution in Go and not in Solidity rigth?

I've been exploring the repo and found this folder called [bindings](https://github.com/ethereum-optimism/supersim/blob/main/bindings) am I in the good direction or not?

**Comment by Ethanol48** [comment]
> @Ethanol48 assigned! let me know if u run into anything

I think this issue is already resolved, in this demonstration of supersim: https://www.youtube.com/live/Kh4fNshcl5Y?t=25m30s, in this extract is shown how to send Ether from L1 to any L2, or I least I think so the transaction of Ether is sent from the L1, and I tested this workflow and logs when a deposit is detected.

for example with this message:

```
INFO [11-02|12:56:23.492] OptimismPortal#depositTransaction        chain.id=901 l2TxHash=0xe1aa6ad90633d9caf7afd1a2fb5dd26c2275b838e1d8381dbd7f2e8718a6fea0
```

But one thing to note, the example given in the docs, does not work, I debugged for some hours and I saw the video showing another method that worked, I think the method in the docs is deprecated, later today I'll create a PR for the docs with the method in the video
