### ISSUE TITLE
Block timestamp not updating properly

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#60]
Supersim's nodes are not properly updating the block timestamp, making this issue to ensure we look into it.

**Comment by tremarkley** [comment]
@nitaliano @hamdiallam when anvil is in automine mode, if you simulate an `executeMessage` tx with `id.timestamp` set to the most recent block using `debug_traceCall`, then the call will fail [here](https://github.com/ethereum-optimism/optimism/blob/beb5d8743ff7998fecc3b5583cb50a4af8fb6441/packages/contracts-bedrock/src/L2/CrossL2Inbox.sol#L117) since `debug_traceCall` will use the most recent block's timestamp for `block.timestamp`, so you end up with `id.timestamp == block.timestamp`. If you send this call using `eth_sendRawTransaction`, it will succeed since the `block.timestamp` gets set to the next block's timestamp.

**Comment by hamdiallam** [comment]
isn't `id.timestamp` externally supplied by the called, not set by the chain? `id.timestamp` should be the timestamp of the log event in the past. Maybe something i'm missing

**Comment by fainashalts** [comment]
Hi @hamdiallam @nitaliano doesn't look like this is resolved yet! If it is resolved, can someone update the issue? And if not, what's needed to get there/how can I help?

**Comment by jakim929** [comment]
Closing this issue since we set up interval mining at 2s
